//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/InputAction/InputEquipment.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputEquipment : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputEquipment()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputEquipment"",
    ""maps"": [
        {
            ""name"": ""Equipment"",
            ""id"": ""22007d0b-94b3-4859-96f6-ddcb3111f79a"",
            ""actions"": [
                {
                    ""name"": ""AddWepon"",
                    ""type"": ""Button"",
                    ""id"": ""ba8a51da-bf3c-4460-b2c4-f17512b5a88d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""af2daced-e62a-489f-bd0e-97cd16a5a243"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AddWepon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Equipment
        m_Equipment = asset.FindActionMap("Equipment", throwIfNotFound: true);
        m_Equipment_Equip = m_Equipment.FindAction("AddWepon", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Equipment
    private readonly InputActionMap m_Equipment;
    private IEquipmentActions m_EquipmentActionsCallbackInterface;
    private readonly InputAction m_Equipment_Equip;
    public struct EquipmentActions
    {
        private @InputEquipment m_Wrapper;
        public EquipmentActions(@InputEquipment wrapper) { m_Wrapper = wrapper; }
        public InputAction @Equip => m_Wrapper.m_Equipment_Equip;
        public InputActionMap Get() { return m_Wrapper.m_Equipment; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(EquipmentActions set) { return set.Get(); }
        public void SetCallbacks(IEquipmentActions instance)
        {
            if (m_Wrapper.m_EquipmentActionsCallbackInterface != null)
            {
                @Equip.started -= m_Wrapper.m_EquipmentActionsCallbackInterface.OnEquip;
                @Equip.performed -= m_Wrapper.m_EquipmentActionsCallbackInterface.OnEquip;
                @Equip.canceled -= m_Wrapper.m_EquipmentActionsCallbackInterface.OnEquip;
            }
            m_Wrapper.m_EquipmentActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Equip.started += instance.OnEquip;
                @Equip.performed += instance.OnEquip;
                @Equip.canceled += instance.OnEquip;
            }
        }
    }
    public EquipmentActions @Equipment => new EquipmentActions(this);
    public interface IEquipmentActions
    {
        void OnEquip(InputAction.CallbackContext context);
    }
}
